name: Python unit testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - name: Install system packages
      run: >
        sudo apt-get update &&
        export DEBIAN_FRONTEND=noninteractive &&
        sudo add-apt-repository universe &&
        sudo apt-get update &&
        sudo apt-get -y install --no-install-recommends
        autoconf 
        build-essential 
        ca-certificates
        git
        libc6
        liblzo2-dev 
        libtool 
        libudev-dev 
        libusb-1.0-0-dev 
        libhidapi-dev
        libhidapi-libusb0
        pkg-config 
        python
        python-dev 
        python-pip
        python-setuptools 

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run unittests
      run: |
        python -m unittest discover -t . -v
