name: Python unit testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Install system packages
      run: >
        apt-get update &&
        export DEBIAN_FRONTEND=noninteractive &&
        apt-get -y install --no-install-recommends
        autoconf 
        build-essential 
        ca-certificates
        git
        liblzo2-dev 
        libtool 
        libudev-dev 
        libusb-1.0-0-dev 
        libhidapi-dev
        libhidapi-libusb0
        pkg-config 
        python
        python-dev 
        python-pip
        python-setuptools 
        python3-dev &&
        echo "deb https://deb.debian.org/debian bullseye main" >> /etc/apt/sources.list 
        && apt-get update && 
        apt-get -y install libc6

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run unittests
      run: |
        python -m unittest discover -t .
